"""empty message

Revision ID: 012a7ab65ce0
Revises: 285337cfb6e4
Create Date: 2016-08-08 22:36:32.584059

"""

# revision identifiers, used by Alembic.
revision = '012a7ab65ce0'
down_revision = '285337cfb6e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_ad_free', sa.Boolean(), nullable=True))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_column('user', 'is_ad_free')
    ### end Alembic commands ###
